const {test}=require('node:test');const assert=require('node:assert/strict');const vm=require('node:vm');const fs=require('node:fs');const path=require('node:path');
function load(file,db,upstream){const base=path.join(__dirname,'..','api');const secure={setSecurityHeaders(){},rateLimit(){return {ok:true}},applyRateLimitHeaders(){},sameOrigin(){return true}};const box={module:{exports:{}},__dirname:base,require(name){if(name==='../lib/db')return db;if(name==='../lib/security')return secure;if(name==='../lib/authorization')return {};if(name==='../lib/audit')return {};if(name==='../lib/persistent-rate-limit')return {persistentRateLimit:async()=>({ok:true})};return require(path.isAbsolute(name)||name.startsWith('node:')?name:path.resolve(base,name));},URLSearchParams,Buffer,Date,console,AbortSignal,Intl,process:{env:{ARTYOU_APPS_SCRIPT_URL:'https://source.example.test',DATABASE_URL:'mysql://test:test@example.test/unit'}},fetch:upstream||(async()=>{throw Error('Network must not be used');})};vm.runInNewContext(fs.readFileSync(path.join(base,file),'utf8'),box);return box.module.exports;}
function response(){return {headers:{},setHeader(k,v){this.headers[k]=v},status(v){this.code=v;return this},send(v){this.body=v;return this},json(v){this.body=v;return this}};}
test('Public events uses two MySQL reads, filters active events and keeps date identifiers and timestamps',async()=>{const calls=[];const h=load('events.js',{query:async(sql,params)=>{calls.push(sql);return sql.includes('FROM event_dates')?[{event_id:1,id:12,date_label:'Sabato',starts_at:'2027-03-13T19:00:00Z',metadata:'{}'}]:[{id:1,slug:'test',title:'Titolo originale',active:1,metadata:'{}'}]}});const r=response();await h({method:'GET',url:'/api/events?action=public'},r);assert.equal(r.code,200);assert.equal(r.body.storage,'mysql');assert.equal(r.body.events[0].dates[0].id,'12');assert.equal(r.body.events[0].dates[0].start,'2027-03-13T19:00:00.000Z');assert.equal(calls.length,2);assert(calls[0].includes('WHERE active=1'));});
test('Public events returns a JSON service error instead of false success when MySQL is unavailable',async()=>{const h=load('events.js',{query:async()=>{throw Error('Unavailable')}});const r=response();await h({method:'GET',url:'/api/events?action=public'},r);assert.equal(r.code,503);assert.equal(r.body.ok,false);});
test('Show page reads the local template and emits valid, safely closed Event JSON-LD',async()=>{const h=load('spettacolo.js',{query:async()=>[{slug:'verified-show',title:'Titolo </script> originale',description:'Descrizione originale',venue:'Sala',address:'Roma',metadata:'{}',starts_at:'2027-03-13T19:00:00Z',date_label:'Sabato'}]});const r=response();await h({query:{slug:'verified-show'}},r);assert.equal(r.code,200);assert(r.body.includes('<x-dc'));assert(r.body.includes('<h1'));assert(!r.body.includes('<\\/script>'));const raw=r.body.match(/<script type="application\/ld\+json">([\s\S]*?)<\/script>/)[1];const schema=JSON.parse(raw);assert.equal(schema.name,'Titolo </script> originale');assert.equal(schema.startDate,'2027-03-13T19:00:00+01:00');assert(r.body.includes('name="robots" content="index,follow"'));});

test('PayPal bookings are rejected before reaching the legacy source, regardless of a forged browser amount',async()=>{const h=load('artyou.js',{query:async()=>{throw Error('No database access expected')}});const r=response();await h({method:'POST',url:'/api/artyou',body:{action:'prenota',Evento:'show',Nome:'Test',Cognome:'Sandbox',Email:'test@example.test',Posti:1,Privacy:true,Pagamento:'PayPal',Importo:'0.01'}},r);assert.equal(r.code,503);assert.equal(r.body.errore,'pagamento_online_non_disponibile');});

const bookingRequest={method:'POST',url:'/api/artyou',body:{action:'prenota',Evento:'show',Nome:'Test',Cognome:'Sandbox',Email:'test@example.test',Posti:1,Privacy:true,Pagamento:'In cassa'}};
const accepted=async()=>({ok:true,status:200,text:async()=>JSON.stringify({ok:true,codice:'TEST-ORIGINAL-ID',stato:'RISERVATO'})});
test('A failed MySQL mirror returns the original reference with explicit pending persistence, never false MySQL confirmation',async()=>{const h=load('artyou.js',{query:async(sql)=>{if(sql.startsWith('INSERT'))throw Error('Unavailable');return [{id:1}];}},accepted);const r=response();await h(bookingRequest,r);assert.equal(r.code,202);assert.equal(r.body.codice,'TEST-ORIGINAL-ID');assert.equal(r.body.persistenceConfirmed,false);assert.equal(r.body.storage,'reconciliation_pending');assert.match(r.body.avviso,/Non ripetere/);});
test('Successful mirror uses original booking ID and duplicate updates cannot downgrade a paid booking',async()=>{const writes=[];const h=load('artyou.js',{query:async(sql,params)=>{if(sql.startsWith('INSERT')){writes.push({sql,params});return {affectedRows:1};}return [{id:1}];}},accepted);const r=response();await h(bookingRequest,r);assert.equal(r.code,200);assert.equal(r.body.persistenceConfirmed,true);assert.equal(writes[0].params[0],'TEST-ORIGINAL-ID');assert(writes[0].sql.includes("IF(status='PAGATO',status,VALUES(status))"));});

test('Course enrollment requests (no event) are forwarded without MySQL lookup and accept the form consent',async()=>{let sent;const h=load('artyou.js',{query:async()=>{throw Error('No database access expected')}},async(url,opt)=>{sent=JSON.parse(opt.body);return {ok:true,status:200,text:async()=>JSON.stringify({ok:true,id:'ART-1',stato:'Nuova'})};});const r=response();await h({method:'POST',url:'/api/artyou',body:{action:'richiesta',Modulo:'Iscrizioni',Corso:'Improvvisazione 1',Nome:'Test',Cognome:'Sandbox',Email:'test@example.test','Privacy accettata':'Sì'}},r);assert.equal(r.code,200);assert.equal(sent.action,'prenota');assert.equal(sent.Corso,'Improvvisazione 1');});
test('Bookings without consent, and course requests without a course, are rejected',async()=>{const h=load('artyou.js',{query:async()=>[{id:1}]},async()=>{throw Error('Network must not be used')});let r=response();await h({...bookingRequest,body:{...bookingRequest.body,Privacy:undefined}},r);assert.equal(r.body.errore,'privacy_obbligatoria');r=response();await h({method:'POST',url:'/api/artyou',body:{action:'richiesta',Nome:'T',Cognome:'S',Email:'t@example.test','Privacy accettata':'Sì'}},r);assert.equal(r.body.errore,'campi_obbligatori_mancanti');});
test('Server-only fields from the browser never reach the legacy source',async()=>{let sent;const h=load('artyou.js',{query:async()=>[{id:1}]},async(url,opt)=>{sent=JSON.parse(opt.body);return {ok:true,status:200,text:async()=>JSON.stringify({ok:true,codice:'ART-2',stato:'RISERVATO'})};});const r=response();await h({...bookingRequest,body:{...bookingRequest.body,Stato:'PAGATO',ID:'ART-FORGED',adminSecret:'x'}},r);assert.equal(r.code,200);for(const k of ['Stato','ID','adminSecret'])assert(!(k in sent),k);});
