const CFG={SHEET_EVENTI:"Eventi",SHEET_PRENOTAZIONI:"Prenotazioni",EMAIL_ADMIN:"info@artyouroma.it",HOLD_MINUTES:15,INVIA_EMAIL_UTENTE:true};
function setup(){const ss=SpreadsheetApp.getActive();ensureSheet_(ss,CFG.SHEET_EVENTI,["Evento","Titolo","Data","Capienza","Prezzo","Attivo"]);ensureSheet_(ss,CFG.SHEET_PRENOTAZIONI,["ID","Creato","Evento","Nome","Cognome","Email","Telefono","Posti","Stato","ScadenzaHold","Pagamento","Importo","Note"]);}
function doGet(e){try{cleanupExpiredHolds_();if(e&&e.parameter&&e.parameter.disponibilita==="1")return json_({ok:true,disponibilita:getAvailabilityMap_()});if(e&&e.parameter&&e.parameter.evento){const evento=String(e.parameter.evento||"").trim();return json_({ok:true,evento:evento,liberi:getAvailableSeats_(evento)});}return json_({ok:true,servizio:"ARTYOU Booking API",timestamp:new Date().toISOString()});}catch(err){return json_({ok:false,errore:String(err&&err.message||err)});}}
function doPost(e){const lock=LockService.getScriptLock();lock.waitLock(30000);try{cleanupExpiredHolds_();const d=parseBody_(e);const action=String(d.action||d.Azione||"prenota").toLowerCase();if(action==="prenota")return createBooking_(d);if(action==="confermapagamento"||action==="pagato")return confirmPayment_(d);if(action==="annulla")return cancelBooking_(d);return json_({ok:false,errore:"azione_non_valida"});}catch(err){return json_({ok:false,errore:String(err&&err.message||err)});}finally{lock.releaseLock();}}
function createBooking_(d){const evento=String(d.Evento||d.evento||"").trim(),nome=String(d.Nome||d.nome||"").trim(),cognome=String(d.Cognome||d.cognome||"").trim(),email=String(d.Email||d.email||"").trim(),telefono=String(d.Telefono||d.telefono||"").trim(),posti=Math.max(1,parseInt(d.Posti||d.posti||1,10)||1),pagamento=String(d.Pagamento||d.pagamento||"In cassa").trim(),importo=String(d.Importo||d.importo||"").trim();if(!evento)return json_({ok:false,errore:"evento_mancante"});if(!nome)return json_({ok:false,errore:"nome_mancante"});if(!email||!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email))return json_({ok:false,errore:"email_non_valida"});if(!telefono)return json_({ok:false,errore:"telefono_mancante"});const ev=getEvent_(evento);if(!ev)return json_({ok:false,errore:"evento_non_configurato"});if(!ev.attivo)return json_({ok:false,errore:"evento_non_attivo"});const liberi=getAvailableSeats_(evento);if(posti>liberi)return json_({ok:false,errore:"esaurito",liberi:liberi});const online=/paypal|online|carta|stripe/i.test(pagamento),stato=online?"HOLD":"RISERVATO",scadenza=online?new Date(Date.now()+CFG.HOLD_MINUTES*60000):"",id=Utilities.getUuid();SpreadsheetApp.getActive().getSheetByName(CFG.SHEET_PRENOTAZIONI).appendRow([id,new Date(),evento,nome,cognome,email,telefono,posti,stato,scadenza,pagamento,importo,""]);sendAdminEmail_({id,evento,nome,cognome,email,telefono,posti,stato,pagamento,importo,liberiDopo:liberi-posti});if(CFG.INVIA_EMAIL_UTENTE)sendUserEmail_({id,evento,nome,cognome,email,posti,stato,pagamento,importo,holdMinutes:CFG.HOLD_MINUTES});return json_({ok:true,id:id,stato:stato,liberi:liberi-posti,holdMinutes:online?CFG.HOLD_MINUTES:0});}
function confirmPayment_(d){const id=String(d.ID||d.id||"").trim();if(!id)return json_({ok:false,errore:"id_mancante"});const sh=SpreadsheetApp.getActive().getSheetByName(CFG.SHEET_PRENOTAZIONI),v=sh.getDataRange().getValues(),h=indexHeaders_(v[0]);for(let r=1;r<v.length;r++){if(String(v[r][h.ID])!==id)continue;const s=String(v[r][h.Stato]||"").toUpperCase();if(s==="ANNULLATO")return json_({ok:false,errore:"prenotazione_annullata"});if(s==="PAGATO")return json_({ok:true,id:id,stato:"PAGATO"});sh.getRange(r+1,h.Stato+1).setValue("PAGATO");if(h.ScadenzaHold!=null)sh.getRange(r+1,h.ScadenzaHold+1).setValue("");return json_({ok:true,id:id,stato:"PAGATO"});}return json_({ok:false,errore:"prenotazione_non_trovata"});}
function cancelBooking_(d){const id=String(d.ID||d.id||"").trim();if(!id)return json_({ok:false,errore:"id_mancante"});const sh=SpreadsheetApp.getActive().getSheetByName(CFG.SHEET_PRENOTAZIONI),v=sh.getDataRange().getValues(),h=indexHeaders_(v[0]);for(let r=1;r<v.length;r++){if(String(v[r][h.ID])!==id)continue;sh.getRange(r+1,h.Stato+1).setValue("ANNULLATO");if(h.ScadenzaHold!=null)sh.getRange(r+1,h.ScadenzaHold+1).setValue("");return json_({ok:true,id:id,stato:"ANNULLATO"});}return json_({ok:false,errore:"prenotazione_non_trovata"});}
function getAvailabilityMap_(){const sh=SpreadsheetApp.getActive().getSheetByName(CFG.SHEET_EVENTI);if(!sh||sh.getLastRow()<2)return{};const v=sh.getDataRange().getValues(),h=indexHeaders_(v[0]),out={};for(let r=1;r<v.length;r++){const e=String(v[r][h.Evento]||"").trim();if(!e)continue;const a=h.Attivo==null?true:parseBool_(v[r][h.Attivo]);if(a)out[e]=getAvailableSeats_(e);}return out;}
function getAvailableSeats_(evento){const ev=getEvent_(evento);if(!ev)return 0;return Math.max(0,ev.capienza-countActiveSeats_(evento));}
function getEvent_(evento){const sh=SpreadsheetApp.getActive().getSheetByName(CFG.SHEET_EVENTI);if(!sh||sh.getLastRow()<2)return null;const v=sh.getDataRange().getValues(),h=indexHeaders_(v[0]);for(let r=1;r<v.length;r++){if(String(v[r][h.Evento]||"").trim()!==evento)continue;return{evento:evento,titolo:h.Titolo==null?evento:String(v[r][h.Titolo]||evento),data:h.Data==null?"":v[r][h.Data],capienza:Math.max(0,parseInt(v[r][h.Capienza],10)||0),prezzo:h.Prezzo==null?"":v[r][h.Prezzo],attivo:h.Attivo==null?true:parseBool_(v[r][h.Attivo])};}return null;}
function countActiveSeats_(evento){const sh=SpreadsheetApp.getActive().getSheetByName(CFG.SHEET_PRENOTAZIONI);if(!sh||sh.getLastRow()<2)return 0;const v=sh.getDataRange().getValues(),h=indexHeaders_(v[0]),now=new Date();let used=0;for(let r=1;r<v.length;r++){if(String(v[r][h.Evento]||"").trim()!==evento)continue;const s=String(v[r][h.Stato]||"").toUpperCase(),p=Math.max(0,parseInt(v[r][h.Posti],10)||0);if(s==="PAGATO"||s==="RISERVATO"){used+=p;continue;}if(s==="HOLD"){const ex=v[r][h.ScadenzaHold],dt=ex instanceof Date?ex:new Date(ex);if(dt&&!isNaN(dt.getTime())&&dt>now)used+=p;}}return used;}
function cleanupExpiredHolds_(){const sh=SpreadsheetApp.getActive().getSheetByName(CFG.SHEET_PRENOTAZIONI);if(!sh||sh.getLastRow()<2)return;const v=sh.getDataRange().getValues(),h=indexHeaders_(v[0]),now=new Date();for(let r=1;r<v.length;r++){if(String(v[r][h.Stato]||"").toUpperCase()!=="HOLD")continue;const ex=v[r][h.ScadenzaHold],dt=ex instanceof Date?ex:new Date(ex);if(dt&&!isNaN(dt.getTime())&&dt<=now)sh.getRange(r+1,h.Stato+1).setValue("SCADUTO");}}
function sendAdminEmail_(b){const subject="Nuova prenotazione Artyou – "+b.evento+" – "+b.posti+" posti",body="Nuova prenotazione\n\nID: "+b.id+"\nEvento: "+b.evento+"\nNome: "+b.nome+" "+b.cognome+"\nEmail: "+b.email+"\nTelefono: "+b.telefono+"\nPosti: "+b.posti+"\nStato: "+b.stato+"\nPagamento: "+b.pagamento+"\nImporto: "+(b.importo||"-")+"\nPosti liberi: "+b.liberiDopo,htmlBody="<h2>Nuova prenotazione Artyou</h2><p><b>Evento:</b> "+esc_(b.evento)+"</p><p><b>Cliente:</b> "+esc_(b.nome+" "+b.cognome)+"</p><p><b>Email:</b> "+esc_(b.email)+"<br><b>Telefono:</b> "+esc_(b.telefono)+"</p><p><b>Posti:</b> "+b.posti+"<br><b>Stato:</b> "+esc_(b.stato)+"<br><b>Pagamento:</b> "+esc_(b.pagamento)+"<br><b>Importo:</b> "+esc_(b.importo||"-")+"</p><p><b>Posti liberi rimanenti:</b> "+b.liberiDopo+"</p><p style='color:#666'>ID: "+esc_(b.id)+"</p>";MailApp.sendEmail({to:CFG.EMAIL_ADMIN,subject:subject,body:body,htmlBody:htmlBody});}
function sendUserEmail_(b){const subject="Prenotazione Artyou – "+b.evento;let stato="La tua prenotazione è registrata.";if(b.stato==="HOLD")stato="I tuoi posti sono bloccati per "+b.holdMinutes+" minuti in attesa del pagamento.";else if(b.stato==="RISERVATO")stato="I tuoi posti sono riservati.";const body="Ciao "+b.nome+",\n\n"+stato+"\n\nEvento: "+b.evento+"\nPosti: "+b.posti+"\nPagamento: "+b.pagamento+"\nImporto: "+(b.importo||"-")+"\nID prenotazione: "+b.id+"\n\nArtyou Roma",htmlBody="<p>Ciao "+esc_(b.nome)+",</p><p>"+esc_(stato)+"</p><p><b>Evento:</b> "+esc_(b.evento)+"<br><b>Posti:</b> "+b.posti+"<br><b>Pagamento:</b> "+esc_(b.pagamento)+"<br><b>Importo:</b> "+esc_(b.importo||"-")+"</p><p style='color:#666'>ID prenotazione: "+esc_(b.id)+"</p><p>Artyou Roma</p>";MailApp.sendEmail({to:b.email,subject:subject,body:body,htmlBody:htmlBody});}
function parseBody_(e){if(!e||!e.postData||!e.postData.contents)return{};try{return JSON.parse(e.postData.contents);}catch(err){return e.parameter||{};}}
function ensureSheet_(ss,name,headers){let sh=ss.getSheetByName(name);if(!sh)sh=ss.insertSheet(name);if(sh.getLastRow()===0)sh.appendRow(headers);return sh;}
function indexHeaders_(headers){const o={};headers.forEach((x,i)=>o[String(x).trim()]=i);return o;}
function parseBool_(v){if(v===true)return true;const s=String(v||"").trim().toLowerCase();return!["0","false","no","off","inattivo"].includes(s);}
function esc_(s){return String(s==null?"":s).replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;").replace(/'/g,"&#039;");}
function json_(o){return ContentService.createTextOutput(JSON.stringify(o)).setMimeType(ContentService.MimeType.JSON);}