'use strict';
const students = Array.from({length:6},(_,i)=>({name:`Studente demo ${i+1}`,plan:['Mensile','Annuale (1 rata)','Annuale (3 rate)'][i%3],amount:[75,570,195][i%3],paid:true}));
const dates=['2026-10-01','2026-10-08','2026-10-15','2026-10-22','2026-10-29'];
const presence=new Map();
const $=id=>document.getElementById(id);
function readable(date){return new Intl.DateTimeFormat('it-IT',{day:'2-digit',month:'short',year:'numeric'}).format(new Date(`${date}T12:00:00`));}
function renderDates(){const chosen=$('lesson').value;$('dates').replaceChildren();$('lesson').replaceChildren();dates.sort().forEach(date=>{const item=document.createElement('span');item.textContent=readable(date);$('dates').append(item);const option=document.createElement('option');option.value=date;option.textContent=readable(date);$('lesson').append(option);});if(dates.includes(chosen))$('lesson').value=chosen;renderAttendance();}
function renderAttendance(){$('attendance').replaceChildren();const date=$('lesson').value;students.forEach((student,i)=>{const row=document.createElement('tr');const name=document.createElement('td');name.textContent=student.name;const cell=document.createElement('td');const check=document.createElement('input');check.type='checkbox';check.setAttribute('aria-label',`Presente: ${student.name}, ${readable(date)}`);check.checked=presence.get(`${date}/${i}`)||false;check.addEventListener('change',()=>presence.set(`${date}/${i}`,check.checked));cell.append(check);row.append(name,cell);$('attendance').append(row);});}
function renderStudents(){$('students').replaceChildren();students.filter(s=>s.name.toLowerCase().includes($('search').value.toLowerCase())).forEach(student=>{const row=document.createElement('tr');[student.name,student.plan,`${student.amount} €`,'Pagato (demo)'].forEach(value=>{const cell=document.createElement('td');cell.textContent=value;row.append(cell);});const cell=document.createElement('td');const button=document.createElement('button');button.textContent='Dettagli';button.setAttribute('aria-label',`Dettagli di ${student.name}`);button.addEventListener('click',()=>{$('detail-text').textContent=`${student.name} · ${student.plan} · ${student.amount} €. Dati dimostrativi; scadenze e storico non collegati.`;$('detail').showModal();});cell.append(button);row.append(cell);$('students').append(row);});}
$('date-form').addEventListener('submit',event=>{event.preventDefault();const date=$('new-date').value;if(dates.includes(date)){$('date-status').textContent='Questa data è già presente.';return;}dates.push(date);renderDates();$('lesson').value=date;renderAttendance();$('date-status').textContent='Data aggiunta alla demo.';});$('lesson').addEventListener('change',renderAttendance);$('search').addEventListener('input',renderStudents);$('close-detail').addEventListener('click',()=>$('detail').close());renderDates();renderStudents();
