'use strict';
const ReplicaModel=(()=>{
 const seed=()=>({users:[{id:'u1',nome:'Socio Demo',email:'socio@example.test',ruolo:'Membro',anno:'1',telefono:'',taglia:'M'},{id:'u2',nome:'Docente Demo',email:'docente@example.test',ruolo:'Docente',anno:'',telefono:'',taglia:'M'}],courses:[{id:'c1',nome:'Improvvisazione primo anno',sede:'Sede dimostrativa',anno:'1',posti:15,tessera:true,descrizione:'Corso dimostrativo',inizio:'2026-10-01',fine:'2027-06-30',orario:'21:00',mensile:75,treRate:195,annuale:570,giorni:'Gio',stato:'Pubblicato',docente:'u2'}],campaigns:[{id:'ca1',nome:'Tesseramento demo 2026/2027',descrizione:'Campagna dimostrativa',importo:30,valuta:'EUR',inizio:'2026-09-01',fine:'2027-08-31',stato:'Pubblicata'}],memberships:[],enrollments:[{id:'e1',utente:'u1',corso:'c1',piano:'Mensile',inizio:'2026-10-01',sospesa:false}],lessons:[{id:'l1',corso:'c1',data:'2026-10-01'}],attendance:[],payments:[],expenses:[],refunds:[],transfers:[],drafts:[],archives:[],audit:[]});
 const cents=n=>Math.round(Number(n)*100);
 const uid=()=>crypto.randomUUID();
 function validate(kind,r,s){if(kind==='courses'){if(!Number.isInteger(Number(r.posti))||Number(r.posti)<1)throw Error('Capienza non valida');if(r.fine<r.inizio)throw Error('Fine antecedente all’inizio');}if(['payments','expenses','refunds','transfers'].includes(kind)&&(!Number.isFinite(Number(r.importo))||Number(r.importo)<=0))throw Error('Importo deve essere positivo');if(kind==='campaigns'&&Number(r.importo)<0)throw Error('Importo negativo');if(kind==='memberships'){if(!s.users.some(u=>u.id===r.utente)||!s.campaigns.some(c=>c.id===r.campagna))throw Error('Utente o campagna non validi');if(s.memberships.some(x=>x.id!==r.id&&x.utente===r.utente&&x.campagna===r.campagna))throw Error('Tessera già assegnata');}if(kind==='enrollments'){const c=s.courses.find(x=>x.id===r.corso);if(!c||!s.users.some(u=>u.id===r.utente))throw Error('Corso o utente non valido');if(s.enrollments.some(e=>e.id!==r.id&&e.utente===r.utente&&e.corso===r.corso))throw Error('Iscrizione già presente');if(s.enrollments.filter(e=>e.id!==r.id&&e.corso===r.corso&&!e.sospesa).length>=Number(c.posti)&&!r.sospesa)throw Error('Corso completo');if(c.tessera&&!s.memberships.some(m=>m.utente===r.utente&&m.stato==='Attiva'&&s.campaigns.some(a=>a.id===m.campagna&&a.inizio<=r.inizio&&a.fine>=r.inizio)))throw Error('Serve tessera attiva alla data di iscrizione');}if(kind==='lessons'){const c=s.courses.find(c=>c.id===r.corso);if(!c||r.data<c.inizio||r.data>c.fine)throw Error('Data fuori dal periodo del corso');if(s.lessons.some(l=>l.id!==r.id&&l.corso===r.corso&&l.data===r.data))throw Error('Lezione già presente');}if(kind==='payments'&&!s.enrollments.some(e=>e.id===r.iscrizione))throw Error('Iscrizione non valida');}
 function save(s,kind,r){validate(kind,r,s);const i=s[kind].findIndex(x=>x.id===r.id);const value={...r,id:r.id||uid()};if(i<0)s[kind].push(value);else s[kind][i]=value;s.audit.push({data:new Date().toISOString(),azione:i<0?'creazione':'modifica',tipo:kind,id:value.id});return value;}
 function balance(s){const incoming=s.payments.reduce((a,p)=>a+cents(p.importo),0)+s.memberships.reduce((a,m)=>a+cents(s.campaigns.find(c=>c.id===m.campagna)?.importo||0),0);const outgoing=s.expenses.filter(e=>e.tipo==='Generale').reduce((a,e)=>a+cents(e.importo),0);return {incoming,outgoing,net:incoming-outgoing};}
 function courseBalance(s,id){const incoming=s.payments.filter(p=>s.enrollments.some(e=>e.id===p.iscrizione&&e.corso===id)).reduce((a,p)=>a+cents(p.importo),0);const expenses=s.expenses.filter(e=>e.tipo==='Per Corso'&&(e.corsi||[]).includes(id)).reduce((a,e)=>a+cents(e.importo)/(e.corsi.length||1),0);const c=s.courses.find(c=>c.id===id);const teacherRefunds=s.refunds.filter(r=>r.docente===c?.docente).reduce((a,r)=>a+cents(r.importo)/Math.max(1,s.courses.filter(x=>x.docente===c.docente&&x.stato==='Pubblicato').length),0);return {incoming,outgoing:Math.round(expenses+teacherRefunds),net:incoming-Math.round(expenses+teacherRefunds)};}
 function schedule(s,e){const c=s.courses.find(c=>c.id===e.corso);if(!c)return [];let d=new Date(e.inizio+'T12:00:00Z');const end=new Date(c.fine+'T12:00:00Z');const out=[];const day=d.getUTCDate();const step=e.piano==='Annuale (3 rate)'?3:e.piano==='Annuale (1 rata)'?12:1;const amount=e.piano==='Annuale (3 rate)'?c.treRate:e.piano==='Annuale (1 rata)'?c.annuale:c.mensile;while(d<=end&&out.length<120){out.push({data:d.toISOString().slice(0,10),importo:amount});const month=d.getUTCMonth()+step;d=new Date(Date.UTC(d.getUTCFullYear(),month,1,12));d.setUTCDate(Math.min(day,new Date(Date.UTC(d.getUTCFullYear(),d.getUTCMonth()+1,0)).getUTCDate()));if(e.piano==='Annuale (1 rata)'||e.piano==='Annuale (3 rate)'&&out.length===3)break;}return out;}
 function paymentReport(s,e,today){let budget=s.payments.filter(p=>p.iscrizione===e.id).reduce((a,p)=>a+cents(p.importo),0);const rows=schedule(s,e).map(r=>{const due=cents(r.importo);const paid=budget>=due;budget=Math.max(0,budget-due);return {...r,paid};});return {paid:rows.filter(r=>r.paid).length,total:rows.length,late:rows.filter(r=>!r.paid&&r.data<today).length,next:rows.find(r=>!r.paid)?.data||'Completato'};}
 function archive(s,label,cutoff){const before=JSON.parse(JSON.stringify(s));before.archives=[];const rec={id:uid(),nome:label,data:cutoff,snapshot:before};s.archives.push(rec);const closed=s.courses.filter(c=>c.fine<=cutoff).map(c=>c.id);s.courses=s.courses.filter(c=>!closed.includes(c.id));const en=s.enrollments.filter(e=>closed.includes(e.corso)).map(e=>e.id);s.enrollments=s.enrollments.filter(e=>!en.includes(e.id));s.payments=s.payments.filter(p=>p.data>cutoff&&!en.includes(p.iscrizione));s.lessons=s.lessons.filter(l=>!closed.includes(l.corso));s.attendance=s.attendance.filter(a=>s.lessons.some(l=>l.id===a.lezione));s.expenses=s.expenses.filter(e=>e.data>cutoff);s.refunds=s.refunds.filter(e=>e.data>cutoff);s.transfers=s.transfers.filter(e=>e.data>cutoff);s.memberships=s.memberships.filter(m=>s.campaigns.find(c=>c.id===m.campagna)?.fine>cutoff);return rec;}
 return {seed,cents,uid,save,balance,courseBalance,schedule,paymentReport,archive};
})();
if(typeof module!=='undefined')module.exports=ReplicaModel;
